### PR TITLE
Remove re-slicing for multipart

### LINKED ISSUE #843: Complete multipart upload fails with timeout
test_multipart_upload at s3tests_boto3/functional/test_s3_neofs.py

We create a multipart upload, upload parts, then try to complete it and fail on timeout:

```
2023-10-11T00:11:51.416Z	debug	layer/multipart_upload.go:629	part details	{"reqId": "6046e93a-4bc4-4401-a4ec-7bb92968286a", "bucket": "yournamehere-cl96tp4ul4bvyi6i-2", "cid": "8E8VhzySor5D5KWSNTpwiSKuu6afVvDmVzJffGmnDf1g", "object": "mymultipart", "upload id": "08bfda57-93e3-4898-b2fc-9df9384d12e0", "part numbers": [3, 2, 4, 5, 1, 6], "oids": ["EfgAgV5k82WaagxVRSmzhEJVoujq6eejm6ofHvd8iBkE", "HerSXJEZzBGZDqMk6Esj8xahWsTMzZfbQPxxnvqCSrhn", "6rdwrex8kvV7LEPY3h47dL3YyYR88pyPNP5GjgWSEZsE", "3nzFgKZBfyBC2oyAJnihgdezcCfEsUWJUpi5xR5qLNNG", "9gnu1Esq6tgwYnKSWBf5m3XSs9XJWK8UksVPPWGfCXYb", "HU1JbiFiSxeH4narXqXpgFZZZorcyF9toUNYKpCaieF8"]}
2023-10-11T00:12:44.473Z	debug	layer/object.go:252	put object	{"reqId": "6046e93a-4bc4-4401-a4ec-7bb92968286a", "bucket": "yournamehere-cl96tp4ul4bvyi6i-2", "cid": "8E8VhzySor5D5KWSNTpwiSKuu6afVvDmVzJffGmnDf1g", "object": "mymultipart", "oid": "HS45zgdNH3et4amxMgUg3CWXwGodhTRiG4pztMnwhrVL"}
2023-10-11T00:12:51.459Z	warn	layer/multipart_upload.go:467	could not delete upload part	{"object id": "6rdwrex8kvV7LEPY3h47dL3YyYR88pyPNP5GjgWSEZsE", "bucket id": "8E8VhzySor5D5KWSNTpwiSKuu6afVvDmVzJffGmnDf1g", "error": "mark object removal via connection pool: remove object via client: delete object on client: rpc error: code = Canceled desc = context canceled"}
2023-10-11T00:12:51.460Z	warn	layer/multipart_upload.go:467	could not delete upload part	{"object id": "3nzFgKZBfyBC2oyAJnihgdezcCfEsUWJUpi5xR5qLNNG", "bucket id": "8E8VhzySor5D5KWSNTpwiSKuu6afVvDmVzJffGmnDf1g", "error": "mark object removal via connection pool: failed to collect relatives: failed to get raw object header: read object header via client: write request: rpc error: code = Canceled desc = context canceled"}
2023-10-11T00:12:51.461Z	warn	layer/multipart_upload.go:467	could not delete upload part	{"object id": "9gnu1Esq6tgwYnKSWBf5m3XSs9XJWK8UksVPPWGfCXYb", "bucket id": "8E8VhzySor5D5KWSNTpwiSKuu6afVvDmVzJffGmnDf1g", "error": "mark object removal via connection pool: failed to collect relatives: failed to get raw object header: read object header via client: write request: rpc error: code = Canceled desc = context canceled"}
2023-10-11T00:12:51.461Z	warn	layer/multipart_upload.go:467	could not delete upload part	{"object id": "HU1JbiFiSxeH4narXqXpgFZZZorcyF9toUNYKpCaieF8", "bucket id": "8E8VhzySor5D5KWSNTpwiSKuu6afVvDmVzJffGmnDf1g", "error": "mark object removal via connection pool: failed to collect relatives: failed to get raw object header: read object header via client: write request: rpc error: code = Canceled desc = context canceled"}
2023-10-11T00:12:51.462Z	error	handler/util.go:29	call method	{"status": 500, "request_id": "6046e93a-4bc4-4401-a4ec-7bb92968286a", "method": "CompleteMultipartUpload", "bucket": "yournamehere-cl96tp4ul4bvyi6i-2", "object": "mymultipart", "description": "could not complete multipart upload", "error": "failed to remove node: rpc error: code = Canceled desc = context canceled", "uploadID": "08bfda57-93e3-4898-b2fc-9df9384d12e0", "Key": "mymultipart"}
```

## Regression
Not sure if it ever worked, but it definitely should

Full logs - [containers_logs.tar.gz](https://github.com/nspcc-dev/neofs-s3-gw/files/12863225/containers_logs.tar.gz)

### PR DESCRIPTION
**Pull request by smallhive**
Closes #843

### CODE REVIEW

**Comment by smallhive** [comment]
Rebased

File: api/layer/multipart_upload.go [hunk 1]
```diff
@@ -201,35 +206,120 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+	lastPart, err := n.treeService.GetLastPart(ctx, bktInfo, multipartInfo.ID)
 	if err != nil {
-		return nil, err
+		// if ErrPartListIsEmpty, there is the first part of multipart.
+		if !errors.Is(err, ErrPartListIsEmpty) {
+			return nil, fmt.Errorf("getLastPart: %w", err)
+		}
+	} else {
+		// try to restore hash state from the last part.
+		if binaryUnmarshaler, ok := multipartHash.(encoding.BinaryUnmarshaler); ok {
```
Comment (carpawell) [inline api/layer/multipart_upload.go:245]: on the one hand, the required interface is guaranteed according to the docs and on the other hand, you do nothing if progress is not unmarshalled so it may lead to hard-to-find bug, so i would just cast without any checks

the same about marshling

File: api/layer/multipart_upload.go [hunk 2]
```diff
@@ -243,12 +333,32 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
-		ETag:     hex.EncodeToString(hash),
+		ETag:     hex.EncodeToString(currentPartHash.Sum(nil)),
 		Created:  prm.CreationTime,
+		Elements: elements,
+	}
+
+	// encoding hash.Hash state to save it in tree service.
+	if binaryMarshaler, ok := multipartHash.(encoding.BinaryMarshaler); ok {
+		partInfo.MultipartHash, err = binaryMarshaler.MarshalBinary()
+
```
Comment (carpawell) [inline api/layer/multipart_upload.go:344]: useless line i guess

File: api/layer/multipart_upload.go [hunk 3]
```diff
@@ -201,35 +206,120 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+		isSetSplitPreviousID = true
+		splitPreviousID = lastPart.OID
 	}
 
+	var (
+		id           oid.ID
+		elements     []string
+		creationTime = TimeNow(ctx)
+		// User may upload part large maxObjectSize in NeoFS. From users point of view it is a single object.
```
Comment (carpawell) [inline api/layer/multipart_upload.go:267]: not sure i can understand this comment properly. I've read something about ETag (the only thing this var is used for) but cannot correlate it with this comment. can you please extend it or tell me what a reader should understand here?

File: api/layer/layer.go [hunk 4]
```diff
@@ -266,13 +268,20 @@ func (f MsgHandlerFunc) HandleMessage(ctx context.Context, msg *nats.Msg) error
 // NewLayer creates an instance of a layer. It checks credentials
 // and establishes gRPC connection with the node.
 func NewLayer(log *zap.Logger, neoFS NeoFS, config *Config) Client {
+	buffers := sync.Pool{}
+	buffers.New = func() any {
+		b := make([]byte, neoFS.MaxObjectSize())
```
Comment (carpawell) [inline api/layer/layer.go:273]: IMO, a potential OOM killer is here, the same way we already fixed this in SDK

File: api/layer/multipart_upload.go [hunk 5]
```diff
@@ -201,35 +206,120 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+		Container:       bktInfo.CID,
+		Creator:         bktInfo.Owner,
+		Attributes:      attributes,
+		CreationTime:    creationTime,
+		CopiesNumber:    multipartInfo.CopiesNumber,
+		SplitID:         multipartInfo.SplitID,
+		MultipartHashes: multipartHashes,
+	}
+
+	dt := n.buffers.Get()
```
Comment (carpawell) [inline api/layer/multipart_upload.go:287]: not critical but dt?.. data? destination?

File: api/layer/multipart_upload.go [hunk 6]
```diff
@@ -201,35 +206,120 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+	chunk := dt.(*[]byte)
+
+	// slice part manually. Simultaneously considering the part is a single object for user.
+	for {
+		if isSetSplitPreviousID {
+			prm.SplitPreviousID = &splitPreviousID
+		}
+
+		nBts, readErr := payloadReader.Read(*chunk)
+		if nBts > 0 {
```
Comment (carpawell) [inline api/layer/multipart_upload.go:297]: what if we have read lets say 10 bytes? building neofs objects that with this size? as i understand that is just a HTTP body

File: api/layer/multipart_upload.go [hunk 7]
```diff
@@ -201,35 +206,120 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+			prm.PayloadSize = uint64(nBts)
+
+			id, _, err = n.objectPutAndHash(ctx, prm, bktInfo)
+			if err != nil {
+				return nil, err
+			}
+
+			isSetSplitPreviousID = true
+			splitPreviousID = id
+			elements = append(elements, id.String())
```
Comment (carpawell) [inline api/layer/multipart_upload.go:308]: according to the usage of this var it seems to me that storing just raw ID is more efficient

File: internal/neofs/neofs.go [hunk 8]
```diff
@@ -345,6 +376,52 @@ func (x *NeoFS) CreateObject(ctx context.Context, prm layer.PrmObjectCreate) (oi
 	return writer.GetResult().StoredObjectID(), nil
 }
 
+// PrepareMulptipartHeader implements neofs.NeoFS interface method.
+func (x *NeoFS) PrepareMulptipartHeader(ctx context.Context, header object.Object, metaChecksum hash.Hash, homomorphicChecksum hash.Hash, payloadLength uint64) (*object.Object, error) {
```
Comment (carpawell) [inline internal/neofs/neofs.go:380]: according to the description to that struct, it is "connection to the NeoFS network",  do we really want it to have such helper funcs? neofs knows nothing about "multiparts"

File: cmd/s3-gw/app_settings.go [hunk 9]
```diff
@@ -413,6 +413,8 @@ func newLogger(v *viper.Viper) *Logger {
 		panic(fmt.Sprintf("build zap logger instance: %v", err))
 	}
 
+	zap.ReplaceGlobals(l)
```
Comment (carpawell) [inline cmd/s3-gw/app_settings.go:416]: some comments to the commit's body about why we want it?

**Review by carpawell — COMMENTED** [review]
Can the internal slicer option ever be turned off?

File: api/layer/multipart_upload.go (hunk 6 above)
Comment (carpawell) [reply api/layer/multipart_upload.go:297]: so maybe reading at least some meaningful bytes number? a 10-byte object in a split for a 1TB object scares me (but TBH, i am not sure if it is possible to read HTTP body partially, i guess it is)

Comment (roman-khimov) [reply api/layer/multipart_upload.go:297]: If anyone is pushing 10B parts what can we do about that? Deny (but it's a valid chunk)? Cache (where?)?

Comment (carpawell) [reply api/layer/multipart_upload.go:297]: i meant we are reading http's body. if is it 10-byte long, no problem. but what if it is 60mb long but only 10 bytes were read by a reader and no EOF returned? current code creates 10-byte NeoFS object

Comment (roman-khimov) [reply api/layer/multipart_upload.go:297]: If you're concerned about premature `Read` (_highly_ unlikely) exit we can check `nBts` wrt upload size declared in parameters.

File: api/layer/multipart_upload.go [hunk 10]
```diff
@@ -245,8 +333,28 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
 		Created:  prm.CreationTime,
+		Elements: elements,
+	}
+
+	// encoding hash.Hash state to save it in tree service.
+	if binaryMarshaler, ok := multipartHash.(encoding.BinaryMarshaler); ok {
+		partInfo.MultipartHash, err = binaryMarshaler.MarshalBinary()
+
+		if err != nil {
+			return nil, fmt.Errorf("marshalBinary: %w", err)
```
Comment (cthulhu-rider) [inline api/layer/multipart_upload.go:346]: again _what_

File: api/layer/multipart_upload.go [hunk 11]
```diff
@@ -410,6 +517,49 @@ func (n *layer) CompleteMultipartUpload(ctx context.Context, p *CompleteMultipar
 		if _, err = completedPartsHeader.WriteString(partInfoStr); err != nil {
 			return nil, nil, err
 		}
+
+		if part.PartNumber > lastPartID {
+			lastPartID = part.PartNumber
+		}
+
+		var o oid.ID
```
Comment (cthulhu-rider) [inline api/layer/multipart_upload.go:486]: could be avoided if we append first and decode last element after

File: api/layer/multipart_upload.go [hunk 12]
```diff
@@ -410,6 +517,49 @@ func (n *layer) CompleteMultipartUpload(ctx context.Context, p *CompleteMultipar
...
+	}
+
+	multipartHash := sha256.New()
+	var homoHash hash.Hash
+	var splitPreviousID oid.ID
+
+	if lastPartID > 0 {
+		lastPart := partsInfo[lastPartID]
+
+		if lastPart != nil {
```
Comment (cthulhu-rider) [inline api/layer/multipart_upload.go:503]: in what case this could be false?

File: api/layer/multipart_upload.go [hunk 13]
```diff
@@ -410,6 +517,49 @@ func (n *layer) CompleteMultipartUpload(ctx context.Context, p *CompleteMultipar
...
+			if len(lastPart.MultipartHash) > 0 {
+				splitPreviousID = lastPart.OID
+
+				if binaryUnmarshaler, ok := multipartHash.(encoding.BinaryUnmarshaler); ok && len(lastPart.MultipartHash) > 0 {
```
Comment (cthulhu-rider) [inline api/layer/multipart_upload.go:507]: 2nd operand is always true here

File: api/layer/multipart_upload.go [hunk 14]
```diff
@@ -410,6 +517,49 @@ func (n *layer) CompleteMultipartUpload(ctx context.Context, p *CompleteMultipar
...
+					if err = binaryUnmarshaler.UnmarshalBinary(lastPart.MultipartHash); err != nil {
+						return nil, nil, fmt.Errorf("unmarshalBinary: %w", err)
+					}
+				}
+			}
+
+			if n.neoFS.IsHomomorphicEnabled() && len(lastPart.HomoHash) > 0 {
+				homoHash = tz.New()
+
+				if binaryUnmarshaler, ok := homoHash.(encoding.BinaryUnmarshaler); ok && len(lastPart.MultipartHash) > 0 {
```
Comment (cthulhu-rider) [inline api/layer/multipart_upload.go:517]: `&& len(lastPart.HomoHash)`? If so, it is also true here

File: internal/neofs/neofs.go (hunk 8 above)
Comment (cthulhu-rider) [reply internal/neofs/neofs.go:380]: agree with @carpawell. This could be generic `FinalizeObjectWithPayloadChecksums` (caller can set payload size by himself)

btw typo in name

File: internal/neofs/neofs.go [hunk 15]
```diff
@@ -345,6 +376,52 @@ func (x *NeoFS) CreateObject(ctx context.Context, prm layer.PrmObjectCreate) (oi
...
+		var csHomoBytes [tz.Size]byte
+		copy(csHomoBytes[:], homomorphicChecksum.Sum(nil))
+
+		cs.SetTillichZemor(csHomoBytes)
+		header.SetPayloadHomomorphicHash(cs)
+	}
+
+	header.SetPayloadSize(payloadLength)
+
+	id, err := header.CalculateID()
```
Comment (cthulhu-rider) [inline internal/neofs/neofs.go:401]: could be done via `header.SetIDWithSignature(x.signer(ctx))`

File: internal/neofs/neofs.go [hunk 16]
```diff
@@ -468,6 +545,16 @@ func (x *NeoFS) DeleteObject(ctx context.Context, prm layer.PrmObjectDelete) err
 	return nil
 }
 
+// MaxObjectSize returns max single object size in bytes in NeoFS.
```
Comment (cthulhu-rider) [inline internal/neofs/neofs.go:548]: not really: it returns configured payload size limit for object slicing when enabled. And i doubt this is needed at all

File: internal/neofs/neofs.go [hunk 17]
```diff
@@ -468,6 +545,16 @@ func (x *NeoFS) DeleteObject(ctx context.Context, prm layer.PrmObjectDelete) err
...
+func (x *NeoFS) MaxObjectSize() int64 {
+	return x.cfg.MaxObjectSize
+}
+
+// IsHomomorphicEnabled shows if homomorphic hashing is enabled in NeoFS.
```
Comment (cthulhu-rider) [inline internal/neofs/neofs.go:553]: same: just a config

File: internal/neofs/tree.go [hunk 18]
```diff
@@ -968,6 +981,36 @@ func (c *TreeClient) GetParts(ctx context.Context, bktInfo *data.BucketInfo, mul
 	return result, nil
 }
 
+func (c *TreeClient) GetLastPart(ctx context.Context, bktInfo *data.BucketInfo, multipartNodeID uint64) (*data.PartInfo, error) {
+	parts, err := c.GetParts(ctx, bktInfo, multipartNodeID)
+	if err != nil {
+		return nil, fmt.Errorf("getParts: %w", err)
```
Comment (cthulhu-rider) [inline internal/neofs/tree.go:987]: clear text pls

File: internal/neofs/neofs.go [hunk 19]
```diff
@@ -270,6 +275,32 @@ func (x *NeoFS) CreateObject(ctx context.Context, prm layer.PrmObjectCreate) (oi
 	obj.SetAttributes(attrs...)
 	obj.SetPayloadSize(prm.PayloadSize)
 
+	if prm.SplitID != "" {
+		var split object.SplitID
+		if err := split.Parse(prm.SplitID); err != nil {
+			return oid.ID{}, fmt.Errorf("split parse: %w", err)
```
Comment (cthulhu-rider) [inline internal/neofs/neofs.go:281]: `parse split ID`

**Comment by cthulhu-rider** [comment]
main commit with reslicing removal contains only issue ref which is good for GH but not enough overall. Lets write some text about motivation and used approach

File: internal/neofs/neofs.go (hunk 15 above)
Comment (smallhive) [reply internal/neofs/neofs.go]: Done!

File: internal/neofs/neofs.go (hunk 16 above)
Comment (smallhive) [reply internal/neofs/neofs.go]: Updated

File: internal/neofs/neofs.go (hunk 17 above)
Comment (smallhive) [reply internal/neofs/neofs.go]: Updated

File: internal/neofs/tree.go (hunk 18 above)
Comment (smallhive) [reply internal/neofs/tree.go]: Fixed

File: internal/neofs/neofs.go (hunk 8 above)
Comment (smallhive) [reply internal/neofs/neofs.go]: Renamed

File: api/layer/multipart_upload.go (hunk 1 above)
Comment (smallhive) [reply api/layer/multipart_upload.go:245]: Done

File: api/layer/multipart_upload.go (hunk 5 above)
Comment (smallhive) [reply api/layer/multipart_upload.go:289]: data already occupied for this place, joined with the next line

File: api/layer/multipart_upload.go (hunk 7 above)
Comment (smallhive) [reply api/layer/multipart_upload.go:310]: Updated

File: api/layer/multipart_upload.go [hunk 20]
```diff
@@ -203,34 +206,119 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+		}
+	} else {
+		// try to restore hash state from the last part.
+		if binaryUnmarshaler, ok := multipartHash.(encoding.BinaryUnmarshaler); ok {
+			if err = binaryUnmarshaler.UnmarshalBinary(lastPart.MultipartHash); err != nil {
+				return nil, fmt.Errorf("unmarshalBinary: %w", err)
+			}
+		}
+
+		if n.neoFS.IsHomomorphicEnabled() {
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go]: replaced

File: api/layer/multipart_upload.go [hunk 21]
```diff
@@ -203,34 +206,119 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+	var (
+		id           oid.ID
+		elements     []string
+		creationTime = TimeNow(ctx)
+		// User may upload part large maxObjectSize in NeoFS. From users point of view it is a single object.
+		// We have to calculate the hash from this object separately.
+		currentPartHash = sha256.New()
+	)
+
+	multipartHashes := []hash.Hash{multipartHash, currentPartHash}
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go:271]: renamed

File: api/layer/multipart_upload.go [hunk 22]
```diff
@@ -203,34 +206,119 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+		Creator:         bktInfo.Owner,
+		Attributes:      attributes,
+		CreationTime:    creationTime,
+		CopiesNumber:    multipartInfo.CopiesNumber,
+		SplitID:         multipartInfo.SplitID,
+		MultipartHashes: multipartHashes,
+	}
+
+	dt := n.buffers.Get()
+	chunk := dt.(*[]byte)
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go]: Do you mean just in place buffer like `b := make([]byte, p.size)?` Buffers already works here https://github.com/nspcc-dev/neofs-s3-gw/blob/4717bd84bdb8ed434012da7d0da0dff98947c46f/internal/neofs/neofs.go#L331
and after many tests this approach shows better memory using, rather in place buffer

File: api/layer/multipart_upload.go [hunk 23]
```diff
@@ -203,34 +206,119 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+
+	multipartHashes := []hash.Hash{multipartHash, currentPartHash}
+	if tzHash != nil {
+		multipartHashes = append(multipartHashes, tzHash)
+	}
+
+	prm := PrmObjectCreate{
+		Container:       bktInfo.CID,
+		Creator:         bktInfo.Owner,
+		Attributes:      attributes,
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go]: I don't see the situation when we need it. Do you have a case?

File: internal/neofs/tree.go [hunk 24]
```diff
@@ -55,9 +56,13 @@ const (
 	isUnversionedKV     = "IsUnversioned"
 	isTagKV             = "IsTag"
 	uploadIDKV          = "UploadId"
+	splitIDKV           = "SplitId"
 	partNumberKV        = "Number"
 	sizeKV              = "Size"
 	etagKV              = "ETag"
+	multipartHashKV     = "MultipartHashes"
```
[the remark this answers is not in the document]
Comment (smallhive) [reply internal/neofs/tree.go:63]: Just follow the "tradition" :smile:

File: api/layer/multipart_upload.go (hunk 2 above)
Comment (smallhive) [reply api/layer/multipart_upload.go]: reworked

File: api/layer/layer.go (hunk 4 above)
Comment (smallhive) [reply api/layer/layer.go:273]: Using `sync.Pool` showed better memory using profile after load tests. It Already works here https://github.com/nspcc-dev/neofs-s3-gw/blob/4717bd84bdb8ed434012da7d0da0dff98947c46f/internal/neofs/neofs.go#L331

**Comment by smallhive** [comment]
> What happens if we're to reupload a part?

Everything will be broken. We collect full object hash moving from part to part. If you re-upload any part in the middle, we will have to re-read all parts after it, recalculate hashes, and re-upload parts

File: api/layer/multipart_upload.go [hunk 25]
```diff
@@ -203,34 +206,119 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
-		return nil, err
+		// if ErrPartListIsEmpty, there is the first part of multipart.
+		if !errors.Is(err, ErrPartListIsEmpty) {
+			return nil, fmt.Errorf("getLastPart: %w", err)
+		}
+	} else {
+		// try to restore hash state from the last part.
+		if binaryUnmarshaler, ok := multipartHash.(encoding.BinaryUnmarshaler); ok {
+			if err = binaryUnmarshaler.UnmarshalBinary(lastPart.MultipartHash); err != nil {
+				return nil, fmt.Errorf("unmarshalBinary: %w", err)
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go]: Udated

File: api/layer/multipart_upload.go [hunk 26]
```diff
@@ -203,34 +206,119 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
+	if n.neoFS.IsHomomorphicEnabled() {
+		tzHash = tz.New()
+	}
+
+	lastPart, err := n.treeService.GetLastPart(ctx, bktInfo, multipartInfo.ID)
 	if err != nil {
-		return nil, err
+		// if ErrPartListIsEmpty, there is the first part of multipart.
+		if !errors.Is(err, ErrPartListIsEmpty) {
+			return nil, fmt.Errorf("getLastPart: %w", err)
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go:241]: Udated

File: api/layer/multipart_upload.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (roman-khimov) [reply api/layer/multipart_upload.go]: It's just a suggestion, if it can't simplify anything now then OK.

File: api/layer/multipart_upload.go (hunk 6 above)
Comment (smallhive) [reply api/layer/multipart_upload.go:297]: Updated

**Comment by roman-khimov** [comment]
> Everything will be broken. We collect full object hash moving from part to part. If you re-upload any part in the middle, we will have to re-read all parts after it, recalculate hashes, and re-upload parts

Cool. We need to do this. And that's where per-part IDs can become handy because

> Part numbers can be any number from 1 to 10,000, inclusive. A part number uniquely identifies a part
and also defines its position within the object being created. If you upload a new part using the same
part number that was used with a previous part, the previously uploaded part is overwritten.

And btw,

> Each part must be at least 5 MB in size, except the last part.

**Comment by smallhive** [comment]
> > Everything will be broken. We collect full object hash moving from part to part. If you re-upload any part in the middle, we will have to re-read all parts after it, recalculate hashes, and re-upload parts
> 
> Cool. We need to do this. And that's where per-part IDs can become handy because
> 
> > Part numbers can be any number from 1 to 10,000, inclusive. A part number uniquely identifies a part
> > and also defines its position within the object being created. If you upload a new part using the same
> > part number that was used with a previous part, the previously uploaded part is overwritten.
> 
> And btw,
> 
> > Each part must be at least 5 MB in size, except the last part.

Added logic for re-upload parts

File: api/layer/multipart_upload.go [hunk 27]
```diff
@@ -203,34 +206,119 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
...
 
-	id, hash, err := n.objectPutAndHash(ctx, prm, bktInfo)
+	if n.neoFS.IsHomomorphicEnabled() {
+		tzHash = tz.New()
+	}
+
+	lastPart, err := n.treeService.GetLastPart(ctx, bktInfo, multipartInfo.ID)
 	if err != nil {
-		return nil, err
+		// if ErrPartListIsEmpty, there is the first part of multipart.
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go:243]: Added

**Review by roman-khimov — APPROVED** [review]
Buffering is the only weakness left here, but we can try optimizing it in future, for now I'd like to see functional requirements met.

**Review by cthulhu-rider — APPROVED** [review]

File: api/layer/layer.go (hunk 4 above)
Comment (carpawell) [reply api/layer/layer.go:273]: > Links to changes, please

https://github.com/nspcc-dev/neofs-sdk-go/pull/539

> Using sync.Pool showed better memory using profile after load tests. It Already works here

yes, but putting 1K objects 1-byte sized simultaneously leads to 64GB memory usage but requires only 1KB in fact. we already know we may be quite successive at running out of _1TB memory_, not a cool story

but ok, as i understand we will return to this later

File: api/layer/neofs_mock.go [hunk 28]
```diff
@@ -194,6 +270,32 @@ func (t *TestNeoFS) CreateObject(_ context.Context, prm PrmObjectCreate) (oid.ID
...
+			return oid.ID{}, fmt.Errorf("split parse: %w", err)
+		}
+		obj.SetSplitID(&split)
+
+		if prm.Multipart.SplitPreviousID != nil {
+			obj.SetPreviousID(*prm.Multipart.SplitPreviousID)
+		}
+
+		if len(prm.Multipart.Children) > 0 {
+			obj.SetChildren(prm.Multipart.Children...)
```
Comment (carpawell) [inline api/layer/neofs_mock.go:285]: @cthulhu-rider, @roman-khimov, @smallhive, just to be sure: we are not implementing v2 object split yet, right?

Comment (roman-khimov) [reply api/layer/neofs_mock.go:285]: Yes, it's to be implemented in the next version. We need to properly test the current scheme and then adapt it to v2.
