### PR TITLE
[#547] s3 tests teardown fix

### LINKED ISSUE #547: Errors during s3-tests teardown
During s3-test teardown, test suit removes all objects and buckets. I see some issues in tree service branch.

1.`invalid cache entry type`

```
2022-06-22T17:46:58.201+0300    warn    cache/objects.go:51     invalid cache entry type        {"actual": "*data.ObjectInfo", "expected": "object.Object"}
```

2. `couldn't cache list of objects` I am not sure this is an actual _error_. This happens during teardown and we have empty bucket before removal. Looks like expected behavior.

```
022-06-22T17:47:28.416+0300    info    api/router.go:167       call method     {"status": 200, "request_id": "0e19d5a2-6952-4b59-a373-58c809702e86", "method": "ListBucketVersions", "description": "OK"}
2022-06-22T17:47:28.539+0300    info    api/router.go:167       call method     {"status": 200, "request_id": "bc1c30e4-04c5-4f19-978f-9fc100f5e1b8", "method": "DeleteMultipleObjects", "description": "OK"}
2022-06-22T17:47:28.543+0300    error   layer/object.go:420     couldn't cache list of objects  {"error": "list versions is empty, cid: GPDxKjSF1XHh43KJGeRCkJGog9zCwVkwbfDTguQFuSvP, prefix: "}
2022-06-22T17:47:32.563+0300    info    api/router.go:167       call method     {"status": 204, "request_id": "06ff3939-7fbd-4b51-bae2-4ef4c50cb86d", "method": "DeleteBucket", "description": "No Content"}
```

### PR DESCRIPTION
**Pull request by KirillovDenis**
close #547

### CODE REVIEW

File: api/layer/multipart_upload.go [hunk 1]
```diff
@@ -228,10 +228,6 @@ func (n *layer) uploadPart(ctx context.Context, multipartInfo *data.MultipartInf
 		HashSum: partInfo.ETag,
 	}
 
-	if err = n.objCache.PutObject(objInfo); err != nil {
-		n.log.Error("couldn't cache system object", zap.Error(err))
-	}
```
Comment (alexvanin) [inline api/layer/multipart_upload.go:233]: Useless because it is a part of multipart object?

**Review by alexvanin — APPROVED** [review]

File: api/layer/multipart_upload.go (hunk 1 above)
Comment (KirillovDenis) [reply api/layer/multipart_upload.go:233]: Useless because all required part info is stored in tree service
