### PR TITLE
Remove XMLName field for CompleteMultipartUpload

### LINKED ISSUE #1074: Gitlab can't upload multipart file
## Current Behavior
```
error	handler/util.go:34	call method	{"status": 400, "request_id": "d2b3504e-56b1-4c7f-8baa-6ade5bd88047", "method": "CompleteMultipartUpload", "bucket": "gitlab-uploads", "object": "@hashed/85/27/8527a891e224136950ff32ca212b45bc93f69fbb801c3b1ebedac52775f99e61/06bff7d16ec44376191f127e052d9e3a/xxx.gz", "description": "could not read complete multipart upload xml", "error": "MalformedXML: 400 => The XML you provided was not well-formed or did not validate against our published schema.", "uploadID": "3puCd9RNj6STyc1GHS5XBuMArRZDyG6K3YbsxHcjFGbk", "Key": "@hashed/85/27/8527a891e224136950ff32ca212b45bc93f69fbb801c3b1ebedac52775f99e61/06bff7d16ec44376191f127e052d9e3a/xxx.gz", "reqId": "d2b3504e-56b1-4c7f-8baa-6ade5bd88047"}
```

## Expected Behavior
200/204.

## Possible Solution
Unknown.

## Steps to Reproduce
Upload big file to GL.

## Your Environment
* Version of the product used: 0.34.1
* Operating System and version (`uname -a`): Debian stable

### PR DESCRIPTION
**Pull request by smallhive**
Gitlab doesn't send this field and AWS docs doesn't say the field is mandatory.

Closes #1074.

### CODE REVIEW

File: api/handler/multipart_upload.go [hunk 1]
```diff
@@ -76,8 +76,7 @@ type (
 	}
 
 	CompleteMultipartUpload struct {
-		XMLName xml.Name               `xml:"http://s3.amazonaws.com/doc/2006-03-01/ CompleteMultipartUpload"`
```
Comment (roman-khimov) [inline api/handler/multipart_upload.go:79]: Do we have any other places like this with xmlns used?

Comment (smallhive) [reply api/handler/multipart_upload.go:79]: Yes, we do. Mostly in responses, but some request structures have this field as well

Comment (roman-khimov) [reply api/handler/multipart_upload.go:79]: Responses are OK, we're generating them and we want to signal our API version. What request structures have it? Can we have the same problem with them as well?

Comment (smallhive) [reply api/handler/multipart_upload.go:79]: - https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1c0fb730bb664e5c2de40c3ce0a08b0dbcce78/api/data/info.go#L83
- https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1c0fb730bb664e5c2de40c3ce0a08b0dbcce78/api/data/locking.go#L9
- https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1c0fb730bb664e5c2de40c3ce0a08b0dbcce78/api/data/locking.go#L30
- https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1c0fb730bb664e5c2de40c3ce0a08b0dbcce78/api/data/locking.go#L25
- https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1c0fb730bb664e5c2de40c3ce0a08b0dbcce78/api/handler/multipart_upload.go#L19, 5 structs one by one
- https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1c0fb730bb664e5c2de40c3ce0a08b0dbcce78/api/handler/notifications.go#L28
- https://github.com/nspcc-dev/neofs-s3-gw/blob/8f1c0fb730bb664e5c2de40c3ce0a08b0dbcce78/api/handler/put.go#L179

Comment (roman-khimov) [reply api/handler/multipart_upload.go:79]: Are there any different versions used by any of these structures? We need to walk through the list and ensure no other input structure has the same problem.

Comment (smallhive) [reply api/handler/multipart_upload.go:79]: Are there any different versions used by any of these structures? I'm not sure I understand what you mean.

All structures are used for requests. I consider all of them have this issue.
Should I remove this tag from all of them?

Comment (roman-khimov) [reply api/handler/multipart_upload.go:79]: > I'm not sure I understand what you mean.

Anything different from http://s3.amazonaws.com/doc/2006-03-01/

>  Should I remove this tag from all of them?

It depends on what exactly the requirements are, we need to look at the spec, look at how things are used, check them against AWS. But mostly likely, yes, for maximum compatibility you need to accept requests without schema specifications.

Comment (smallhive) [reply api/handler/multipart_upload.go:79]: Amazon s3 works perfectly without `xmlns`. I checked all commands with `xmlns` in the requests that we have. Big s3 works with and without _http://s3.amazonaws.com/doc/2006-03-01/_

File: api/handler/response_test.go [hunk 2]
```diff
@@ -14,7 +14,7 @@ func TestAccessControlPolicyXML(t *testing.T) {
 	// https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html
 	var policyTemplate = `
 <?xml version="1.0" encoding="UTF-8"?>
-<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
+<AccessControlPolicy>
```
Comment (roman-khimov) [inline api/handler/response_test.go:17]: I'd prefer to have it in the gateway output. Can we do that?

Comment (smallhive) [reply api/handler/response_test.go:17]: This structure is used for request and response. We may try to duplicate it and use different for each case

Comment (smallhive) [reply api/handler/response_test.go:17]: Updated

File: api/handler/response.go [hunk 3]
```diff
@@ -57,6 +57,12 @@ type Bucket struct {
 
 // AccessControlPolicy contains ACL.
 type AccessControlPolicy struct {
+	XMLName           xml.Name `xml:"AccessControlPolicy" json:"-"`
+	Owner             Owner
+	AccessControlList []*Grant `xml:"AccessControlList>Grant"`
+}
+
+type AccessControlPolicyResponse struct {
```
Comment (roman-khimov) [inline api/handler/response.go:65]: Exported structures must have comments.

**Review by roman-khimov — COMMENTED** [review]
Are there any other structures used for responses among those changed in this PR?

File: api/handler/response.go (hunk 3 above)
Comment (smallhive) [reply api/handler/response.go:66]: Updated

**Review by roman-khimov — APPROVED** [review]
