### PR TITLE
 Fix error when file with policy cannot be read

### LINKED ISSUE #558: Print error "File not found" if a .json file doesn't exist
If not existing filepath is set, authmate tries to parse it anyway and prints the following error:
```
$ authmate issue-secret --container-policy police.json
couldn't parse container policy: invalid character 's' looking for beginning of value
```

It looks confusing because that's the error of a filepath not content of `.json`.

### PR DESCRIPTION
**Pull request by masterSplinter01**
I'm not sure is there a convenient way to differentiate invalid plain-string json and non-existing filepath, that's why `authmate` returns the same error for both cases. But text of the error when file cannot be read become clearer.
 
Closes #558

### CODE REVIEW

File: cmd/s3-authmate/main.go [hunk 1]
```diff
@@ -440,9 +440,16 @@ func parsePolicies(val string) (authmate.ContainerPolicies, error) {
...
-	if err != nil {
+
+	var (
 		data = []byte(val)
+		err  error
+	)
+
+	if !json.Valid(data) {
+		if data, err = os.ReadFile(val); err != nil {
+			return nil, fmt.Errorf("coudln't read json file or its content is invalid")
```
Comment (KirillovDenis) [inline cmd/s3-authmate/main.go:451]: Maybe we should use the following msg: `coudln't read json file or provided json is invalid`.
Since user will see this message when he provided invalid json string

**Review by alexvanin — DISMISSED** [review]
See @KirillovDenis's comment.

**Review by KirillovDenis — APPROVED** [review]
