### PR TITLE
[#364] Support placement policy overriding

### LINKED ISSUE #364: Static empty placementRules parameter in buildPlacementPolicy function in authmate
Setting of custom policy for placing of a container with tokens not working because of authmate/authmate.go:108: 
```
pp, err := buildPlacementPolicy("")
```

### PR DESCRIPTION
**Pull request by KirillovDenis**
closes #364

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

File: authmate/authmate.go [hunk 1]
```diff
@@ -65,6 +64,13 @@ type (
 		ContainerPolicies     ContainerPolicies
 	}
 
+	// ContainerOptions parameters of auth container to put the secret into.
```
Comment (cthulhu-rider) [inline authmate/authmate.go:67]:
```suggestion
	// ContainerOptions groups parameters of auth container to put the secret into.
```

**Review by cthulhu-rider — APPROVED** [review]
