### PR TITLE
Parallel uploads for multipart

### LINKED ISSUE #1020: Parallel uploads for multipart
Multipart uploads don't work in general case

## Current Behavior
AWS SDK uploads _parts_ for _multipart_ in 5 parallel threads. The gate expects parts subsequently one by one

## Expected Behavior
All parts should be uploaded in any order

## Possible Solution
Collect the final object hash in a different way

## Steps to Reproduce
- Create multipart upload with any available tool
- Upload parts in not subsequent order and get `OperationAborted: 409` error

## Context
Related to #1016

## Your Environment

* Version of the product used: [59db6be2c65b89aaa94047d98cb1fb38bc4393c3](https://github.com/nspcc-dev/neofs-s3-gw/commit/968ea3a608db8d7763c03c1dc9f5af7f9c2d87b1)

### PR DESCRIPTION
**Pull request by smallhive**
Closes #1020

### CODE REVIEW

File: api/layer/multipart_upload.go [hunk 1]
```diff
@@ -1184,3 +1250,213 @@ func (n *layer) manualSlice(ctx context.Context, bktInfo *data.BucketInfo, prm P
...
+		return nil, fmt.Errorf("get part by number: %w", err)
+	}
+
+	var (
+		id              oid.ID
+		chunk           *[]byte
+		elements        []data.LinkObjectPayload
+		isReturnToPool  bool
+		splitFirstID    = zeroPart.OID
+		splitPreviousID = zeroPart.OID
```
Comment (roman-khimov) [inline api/layer/multipart_upload.go:1268]: Wow. So it's like a tree starting from the first OID? The idea was to make them completely separate. But if this works maybe it's a better scheme in the end (somewhat easier to clean up).

File: api/layer/multipart_upload.go [hunk 2]
```diff
@@ -1184,3 +1250,213 @@ func (n *layer) manualSlice(ctx context.Context, bktInfo *data.BucketInfo, prm P
...
+		UploadID: params.uploadPartParams.Info.UploadID,
+		Number:   params.uploadPartParams.PartNumber,
+		OID:      id,
+		Size:     params.decSize,
+		ETag:     hex.EncodeToString(currentPartHash.Sum(nil)),
+		Created:  prm.CreationTime,
+		Elements: elements,
+	}
+
+	// encoding hash.Hash state to save it in tree service.
```
Comment (roman-khimov) [inline api/layer/multipart_upload.go:1323]: I think it's not necessary for these parts. These hashes can't be reused.

File: api/layer/multipart_upload.go [hunk 3]
```diff
@@ -1184,3 +1250,213 @@ func (n *layer) manualSlice(ctx context.Context, bktInfo *data.BucketInfo, prm P
...
+	filters.AddFilter(headerS3MultipartUpload, uploadID, object.MatchStringEqual)
+
+	var prmSearch = PrmObjectSearch{
+		Container: bucketInfo.CID,
+		Filters:   filters,
+	}
+
+	n.prepareAuthParameters(ctx, &prmSearch.PrmAuth, bucketInfo.Owner)
+
+	oids, err := n.neoFS.SearchObjects(ctx, prmSearch)
```
Comment (roman-khimov) [inline api/layer/multipart_upload.go:1407]: Will be pain performance-wise, but the only alternative now is the tree.

**Review by roman-khimov — COMMENTED** [review]
Nice overall.

File: api/layer/multipart_upload.go (hunk 1 above)
Comment (smallhive) [reply api/layer/multipart_upload.go:1252]: It is working for the `Slot` part and helps to avoid double reupload

File: api/layer/multipart_upload.go (hunk 2 above)
Comment (smallhive) [reply api/layer/multipart_upload.go:1307]: this method works for all types of parts, for complete reupload too. I prefer to have the single method without extra `if`

File: api/layer/multipart_upload.go [hunk 4]
```diff
@@ -1080,12 +1080,14 @@ func (n *layer) getUploadParts(ctx context.Context, p *UploadInfoParams) (*data.
 			return -1
 		}
 
-		if a.ServerCreated.Before(b.ServerCreated) {
-			return -1
-		}
+		if a.Number == b.Number {
+			if a.ServerCreated.Before(b.ServerCreated) {
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/multipart_upload.go]: Separated

**Review by roman-khimov — APPROVED** [review]
