### PR TITLE
[#542] Fix object removal

### LINKED ISSUE #542: The gw deletes a null object in versioned bucket from NeoFS if version is not specified in a request
`tree-service` branch:

```
$ aws s3api create-bucket --bucket test7 --endpoint-url http://127.0.0.1:8084

$ aws s3api put-object --key a --body ~/cat.txt  --bucket test7 --endpoint-url http://127.0.0.1:8084 
{
  "ETag": "93d30be4ee6dd625821e8b35f93af305f3f084aa595440a5e696d11dbbc6516a"
  
$ aws s3api put-bucket-versioning --versioning-configuration Status=Enabled  --bucket test7 --endpoint-url http://127.0.0.1:8084

$ aws s3api put-object --key a --body ~/cat.txt  --bucket test7 --endpoint-url http://127.0.0.1:8084
{
  "ETag": "93d30be4ee6dd625821e8b35f93af305f3f084aa595440a5e696d11dbbc6516a",
  "VersionId": "EFf9FAJb48X1gkN5Ca4MjYzWVxkGdA7XWPa6X8d57ZD2"
}

$ neofs-cli container list-objects --wallet ~/work/neofs-dev-env/wallets/wallet.json --rpc-endpoint 192.168.130.71:8080  --cid DdPGrNVp5vu9ja7ayEp7SLKZfi8rRosMsBrqW1KN4CEo
Enter password > 
Gqb3zTbsT9aHPwtgyaHpgwGYqcup6yJmCZ12WDA87zU5
EFf9FAJb48X1gkN5Ca4MjYzWVxkGdA7XWPa6X8d57ZD2

$ aws s3api delete-object --key a --bucket test7  --endpoint-url http://127.0.0.1:8084

$ aws s3api list-object-versions --bucket test7 --endpoint-url http://127.0.0.1:8084| jq                                                      ✔ 
{
  "Versions": [
    {
      "ETag": "93d30be4ee6dd625821e8b35f93af305f3f084aa595440a5e696d11dbbc6516a",
      "Size": 110,
      "Key": "a",
      "VersionId": "EFf9FAJb48X1gkN5Ca4MjYzWVxkGdA7XWPa6X8d57ZD2",
      "IsLatest": false,
      "LastModified": "2022-06-17T23:25:04+00:00",
      "Owner": {
        "DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
        "ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
      }
    }
  ],
  "DeleteMarkers": [
    {
      "Owner": {
        "DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
        "ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
      },
      "Key": "a",
      "VersionId": "CTrY8CcKp1AG1AgjSUtPrxCo8zjgM4EkRraUCBauMotr",
      "IsLatest": true,
      "LastModified": "2022-06-17T23:26:35+00:00"
    }
  ]
}


$ neofs-cli container list-objects --wallet ~/work/neofs-dev-env/wallets/wallet.json --rpc-endpoint 192.168.130.71:8080  --cid DdPGrNVp5vu9ja7ayEp7SLKZfi8rRosMsBrqW1KN4CEo
Enter password > 
EFf9FAJb48X1gkN5Ca4MjYzWVxkGdA7XWPa6X8d57ZD2

```

### PR DESCRIPTION
**Pull request by KirillovDenis**
close #542 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

File: api/layer/layer.go [hunk 1]
```diff
@@ -470,72 +471,76 @@ func getRandomOID() (*oid.ID, error) {
...
+			FilePath: obj.Name,
+		},
+		DeleteMarker: &data.DeleteMarkerInfo{
+			Created: time.Now(),
+			Owner:   n.Owner(ctx),
+		},
+		IsUnversioned: !settings.VersioningEnabled,
+	}
+
+	if obj.Error = n.treeService.AddVersion(ctx, &bkt.CID, newVersion); obj.Error != nil {
```
Comment (masterSplinter01) [inline api/layer/layer.go:525]: Why we need to hang delete marker on a tree when bucket is unversioned? 
If I understand correctly we should create delete marker for versioned object. https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeleteMarker.html

Comment (KirillovDenis) [reply api/layer/layer.go:525]: AWS do the same:
```
$ aws s3api --profile aws get-bucket-versioning --bucket dkirillov 
{
    "Status": "Suspended"
}
$ aws s3api --profile aws put-object --bucket dkirillov --key a
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\""
}
$ aws s3api --profile aws list-object-versions --bucket dkirillov 
{
    "Versions": [
        {
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Key": "a",
            "VersionId": "null",
            "IsLatest": true,
            "LastModified": "2022-06-30T06:35:52+00:00",
            "Owner": {
                "ID": "68e12342e5971d09ced74634fc7cc0fc5f01419d06b76353d42ce3108367183b"
            }
        }
    ]
}
$ aws s3api --profile aws delete-object --bucket dkirillov --key a
{
    "DeleteMarker": true,
    "VersionId": "null"
}
$ aws s3api --profile aws list-object-versions --bucket dkirillov 
{
    "DeleteMarkers": [
        {
            "Owner": {
                "ID": "68e12342e5971d09ced74634fc7cc0fc5f01419d06b76353d42ce3108367183b"
            },
            "Key": "a",
            "VersionId": "null",
            "IsLatest": true,
            "LastModified": "2022-06-30T06:36:22+00:00"
        }
    ]
}
```

Comment (masterSplinter01) [reply api/layer/layer.go:525]: Now there is no difference between `suspended` and `unversioned` mode. It should be reconsidered because it seems like we can differ these modes with the new tree service.

File: api/layer/layer.go [hunk 2]
```diff
@@ -470,72 +471,76 @@ func getRandomOID() (oid.ID, error) {
...
+			Created: time.Now(),
+			Owner:   n.Owner(ctx),
+		},
+		IsUnversioned: !settings.VersioningEnabled,
+	}
+
+	if obj.Error = n.treeService.AddVersion(ctx, bkt.CID, newVersion); obj.Error != nil {
+		return obj
+	}
+	n.namesCache.Delete(bkt.Name + "/" + obj.Name)
```
Comment (masterSplinter01) [inline api/layer/layer.go:528]: Shouldn't we clear `listsCache`?

File: api/layer/layer.go [hunk 3]
```diff
@@ -470,72 +471,76 @@ func getRandomOID() (oid.ID, error) {
...
-			return obj
-		}
+	var newVersion *data.NodeVersion
 
-		n.namesCache.Delete(bkt.Name + "/" + obj.Name)
-	} else {
-		if obj.Error != nil {
-			return obj
-		}
+	if !settings.VersioningEnabled {
```
Comment (masterSplinter01) [inline api/layer/layer.go:491]: If have neither `null` version nor existing delete marker, the gw doesn't put any delete marker
```
$ aws s3api create-bucket --bucket test8 --endpoint-url http://127.0.0.1:8084
$ aws s3api put-bucket-versioning --versioning-configuration Status=Enabled --bucket test8 --endpoint-url http://127.0.0.1:8084 
$ aws s3api put-object --key a --body ~/Downloads/cat.jpg   --bucket test8 --endpoint-url http://127.0.0.1:8084
$ aws s3api put-object --key a --body ~/Downloads/cat.jpg   --bucket test8 --endpoint-url http://127.0.0.1:8084
$ aws s3api list-object-versions  --bucket test8 --endpoint-url http://127.0.0.1:8084
{
  "Versions": [
    {
      "ETag": "03719ec2b4558dc89c82c47283b4ab9dd17e6e56d1858f254892707491443536",
      "Size": 87422,
      "Key": "a",
      "VersionId": "8tuhfrMiEdvr3m8QkPdE9jVDXgTMTHcVj18RE74rbLtT",
      "IsLatest": true,
      "LastModified": "2022-07-04T16:34:47+00:00",
      "Owner": {
        "DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
        "ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
      }
    },
    {
      "ETag": "03719ec2b4558dc89c82c47283b4ab9dd17e6e56d1858f254892707491443536",
      "Size": 87422,
      "Key": "a",
      "VersionId": "F4VwNo7x3PvW9Es29uPu9EMZpnKQ5exTwfGJz34D94HM",
      "IsLatest": false,
      "LastModified": "2022-07-04T16:34:45+00:00",
      "Owner": {
        "DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
        "ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
      }
    }
  ]
}
$ aws s3api delete-object --key a --bucket test8  --endpoint-url http://127.0.0.1:8084
$ aws s3api list-object-versions  --bucket test8 --endpoint-url http://127.0.0.1:8084
{
  "Versions": [
    {
      "ETag": "03719ec2b4558dc89c82c47283b4ab9dd17e6e56d1858f254892707491443536",
      "Size": 87422,
      "Key": "a",
      "VersionId": "8tuhfrMiEdvr3m8QkPdE9jVDXgTMTHcVj18RE74rbLtT",
      "IsLatest": true,
      "LastModified": "2022-07-04T16:34:47+00:00",
      "Owner": {
        "DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
        "ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
      }
    },
    {
      "ETag": "03719ec2b4558dc89c82c47283b4ab9dd17e6e56d1858f254892707491443536",
      "Size": 87422,
      "Key": "a",
      "VersionId": "F4VwNo7x3PvW9Es29uPu9EMZpnKQ5exTwfGJz34D94HM",
      "IsLatest": false,
      "LastModified": "2022-07-04T16:34:45+00:00",
      "Owner": {
        "DisplayName": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM",
        "ID": "NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM"
      }
    }
  ]
}
```
Logs: 
```
could not delete object {"request_id": "84ca3677-d547-4c89-b5e4-aa91077214ed", "bucket_name": "test8", "object_name": "a", "error": "NoSuchKey: 404 => The specified key does not exist."}
```

File: api/layer/layer.go [hunk 4]
```diff
@@ -470,72 +471,76 @@ func getRandomOID() (oid.ID, error) {
...
+			if obj.DeleteMarkVersion, obj.Error = n.removeOldVersion(ctx, bkt, nodeVersion, obj); obj.Error != nil {
+				return obj
+			}
+		} else if !errors.IsS3Error(obj.Error, errors.ErrNoSuchKey) {
 			return obj
 		}
 	}
 
-	n.listsCache.CleanCacheEntriesContainingObject(obj.Name, bkt.CID)
+	randOID, err := getRandomOID()
```
[the remark this answers is not in the document]
Comment (KirillovDenis) [reply api/layer/layer.go:508]: Actually, we can not reduce the umber of requests to the tree service because we have to update node anyway. The reason is to be sure that this node will be the last version (it's required to update timestamp)

**Review by masterSplinter01 — APPROVED** [review]
