### PR TITLE
s3 pagination failures

### LINKED ISSUE #1175: s3 pagination failures
https://github.com/nspcc-dev/neofs-testcases/pull/1066 - tests are here

1. using cli (test_s3_pagination_in_objects_versions_listing_via_cli) - ```aws --no-verify-ssl  --profile profile__FoMEOq5RS9 s3api list-object-versions --bucket 4823586c-cbcb-45f8-9a2b-21a4e0ea7457 --endpoint https://localhost:50071 --page-size 5```
hangs infinitely, but should return first 5 elements
2. using boto3 (test_s3_pagination_in_objects_versions_listing_via_boto3):
```
            paginator = self.s3_client.get_paginator("list_object_versions")
            pages = paginator.paginate(Bucket=bucket, PaginationConfig={"PageSize": 5, "MaxItems": objects_count})
            results = []
>           for page in pages:
```
fails with:
```
E                   botocore.exceptions.PaginationError: Error during pagination: The same next token was received twice: {'KeyMarker': 'temp_file_453b5a6b-dda3-45ef-bdd0-815c2004038b', 'VersionIdMarker': 'DF99d361CQXNa8PBCwurpYuv36MGMe1ATJXGVjgtYCUo'}
```

### PR DESCRIPTION
**Pull request by smallhive**
Closes #1175

The tests themselves need to be updated as well

### CODE REVIEW

**Comment by smallhive** [comment]
**Change 1**

This subpart of the `test_s3_pagination_in_objects_versions_listing_via_boto3` fails each time, even without S3 gate communication

```python
...
        with allure.step("Check pagination with starting token"):
            paginator = self.s3_client.get_paginator("list_object_versions")
    
            next_token = None
            all_versions = []
    
            while True:
                pagination_args = {"Bucket": bucket, "PaginationConfig": {"PageSize": 5}}
                if next_token:
                    pagination_args["PaginationConfig"]["StartingToken"] = next_token
    
                page_iterator = paginator.paginate(**pagination_args)
>               page = next(page_iterator)
E               TypeError: 'PageIterator' object is not an iterator
```
with error
```
FAILED pytest_tests/tests/s3/test_s3_versioning.py::TestS3Versioning::test_s3_pagination_in_objects_versions_listing_via_boto3[boto3] - TypeError: 'PageIterator' object is not an iterator
```

**Comment by smallhive** [comment]
** Change 3**

inside `test_s3_pagination_in_objects_versions_listing_via_cli`
```
assert len(versions) == max_keys, f"Expected {max_keys} versions, got {len(versions)}"
```
replace with
```
assert len(versions) <= max_keys, f"Expected {max_keys} versions, got {len(versions)}"
```

The reason is [here](https://github.com/nspcc-dev/neofs-s3-gw/compare/1175-s3-pagination-failures?expand=1#diff-0dfb2a5ddffd63f0fa4b696362e4e869ddf4f8ab23757e05b51f00d6a0c8a6aaR98).
There are NeoFS search v2 cursor implementation-specific things against `ListObjectVersions` required behaviour

**Comment by evgeniiz321** [comment]
@smallhive
**Change 1** - fixed
**Change 2** - there was just a comparison with a wrong variable there - fixed it as well
** Change 3** - fixed
But tests still fail on the original problem - `The same next token was received twice` from this PR as well

**Comment by roman-khimov** [comment]
@smallhive: all of the explanations belong to the _commit message_. That's exactly what it is for.

File: api/layer/versioning.go [hunk 1]
```diff
@@ -62,12 +86,25 @@ func (n *layer) ListObjectVersions(ctx context.Context, p *ListObjectVersionsPar
...
+		res.NextVersionIDMarker = allObjects[p.MaxKeys-1].ObjectInfo.VersionID()
 
 		allObjects = allObjects[:p.MaxKeys]
-		res.KeyMarker = allObjects[p.MaxKeys-1].ObjectInfo.Name
-		res.VersionIDMarker = allObjects[p.MaxKeys-1].ObjectInfo.VersionID()
+
+		lastIndex := len(allObjects) - 1
+
+		if len(allObjects) >= 2 {
+			if allObjects[lastIndex].ObjectInfo.Name != allObjects[lastIndex-1].ObjectInfo.Name {
```
Comment (roman-khimov) [inline api/layer/versioning.go:97]: What if I have
```
a version 1
a version 2
b version 1
b version 2
.... next page
b version 3
```
?

File: api/layer/versioning.go [hunk 2]
```diff
@@ -1,59 +1,83 @@
...
+			if errors.Is(err, ErrNodeNotFound) {
+				return res, nil
 			}
+			return nil, err
+		}
 
-			if version.NodeVersion.IsUnversioned {
-				isNullVersionCounted = true
+		sortedNames := make([]string, 0, len(versions))
+		for k := range versions {
```
Comment (roman-khimov) [inline api/layer/versioning.go:49]: `slices.Collect(maps.Keys(versions))`?

File: api/layer/object.go [hunk 3]
```diff
@@ -1488,3 +1499,85 @@ func (n *layer) searchEverythingForRemove(ctx context.Context, bkt *data.BucketI
 
 	return oids, nil
 }
+
+func (n *layer) searchAllVersionsInNeoFSWithCursor(ctx context.Context, bkt *data.BucketInfo, owner user.ID, objectName, cursor string) ([]allVersionsSearchResult, string, error) {
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/object.go]: Updated

File: api/layer/versioning.go (hunk 1 above)
Comment (smallhive) [reply api/layer/versioning.go:95]: Exactly in your case, it will be ok. But unfortunately, ListObjectVersion works like:

```
a version 2
a version 1
b version 3
b version 2
.... next page
b version 1
```

Thus we have a problem, because we will return in the next page
```
b version 3
b version 2
```

This case requires further investigation

File: api/layer/object.go [hunk 4]
```diff
@@ -408,90 +408,9 @@ func (n *layer) prepareMultipartHeadObject(ctx context.Context, p *PutObjectPara
...
-			if err != nil {
-				return nil, fmt.Errorf("invalid payload size %s: %w", item.Attributes[3], err)
-			}
-		}
-
-		psr.IsDeleteMarker = item.Attributes[4] != ""
-
-		searchResults = append(searchResults, psr)
-	}
+	searchResults, _, err := n.searchAllVersionsInNeoFSWithCursor(ctx, bkt, owner, objectName, onlyUnversioned, nil)
```
Comment (roman-khimov) [inline api/layer/object.go:411]: `SearchObjectsV2()` was looping through all the results, this gets one page only. I think it's a regression.

File: api/layer/object.go [hunk 5]
```diff
@@ -1488,3 +1418,103 @@ func (n *layer) searchEverythingForRemove(ctx context.Context, bkt *data.BucketI
 
 	return oids, nil
 }
+
+func (n *layer) searchAllVersionsInNeoFSWithCursor(ctx context.Context, bkt *data.BucketInfo, owner user.ID, objectName string, onlyUnversioned bool, cursor *string) ([]allVersionsSearchResult, string, error) {
```
Comment (roman-khimov) [inline api/layer/object.go:1422]: It'd be easier to handle if this would be located nearby `searchAllVersionsInNeoFS`. The patch would be smaller.

File: api/layer/versioning.go [hunk 6]
```diff
@@ -1,59 +1,83 @@
...
+			sortedNames = append(sortedNames, k)
+		}
+		slices.Sort(sortedNames)
+
+		for _, name := range sortedNames {
+			sortedVersions := versions[name]
+			slices.SortFunc(sortedVersions, func(a, b *data.ExtendedObjectInfo) int {
```
[the remark this answers is not in the document]
Comment (roman-khimov) [reply api/layer/versioning.go:54]: And that's `ListObjectVersions()`, this code can be shared.

File: api/layer/versioning.go (hunk 1 above)
Comment (roman-khimov) [reply api/layer/versioning.go:95]: So, a separate issue?

File: api/layer/object.go (hunk 4 above)
Comment (smallhive) [reply api/layer/object.go:411]: Eventually, it is an optimisation. Now we took the minimum that we could. Before we did _paging_ in the code

File: api/layer/versioning.go [hunk 7]
```diff
@@ -1,59 +1,109 @@
...
+					continue
+				}
+
+				if version.NodeVersion.IsUnversioned {
+					isNullVersionCounted = true
+				}
+
+				// On the next pages we should filter out objects we already showed on the previous page.
+				if p.KeyMarker == version.NodeVersion.FilePath && keyMarkerLastTs > 0 {
+					// Objects are sorder in reverse order. The most recently stored objects are in the beginning.
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/versioning.go]: Fixed :disappointed:

File: api/layer/versioning.go [hunk 8]
```diff
@@ -1,59 +1,109 @@
...
-			if version.NodeVersion.IsUnversioned {
-				isNullVersionCounted = true
+		sortedNames := slices.Collect(maps.Keys(versions))
+		slices.Sort(sortedNames)
+
+		for _, name := range sortedNames {
+			sortedVersions := versions[name]
+			// The object with "null" version should be only one. We get only last (actual) one.
+			var isNullVersionCounted bool
+			var isLatestShoubBeSet = true
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/versioning.go]: Fixed

**Review by roman-khimov — APPROVED** [review]
