### PR TITLE
[#678] Update SDK to fix panic on go1.19

### LINKED ISSUE #678: Update SDK
The same as https://github.com/nspcc-dev/neofs-http-gw/issues/188

### PR DESCRIPTION
**Pull request by KirillovDenis**
close #678 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

File: internal/neofs/tree_signature.go [hunk 1]
```diff
@@ -2,21 +2,15 @@
...
-	"crypto/sha512"
-
+	crypto "github.com/nspcc-dev/neofs-crypto"
 	"google.golang.org/protobuf/proto"
 )
 
 func (c *TreeClient) signData(buf []byte, f func(key, sign []byte)) error {
-	hash := sha512.Sum512(buf)
-	x, y, err := ecdsa.Sign(rand.Reader, &c.key.PrivateKey, hash[:])
+	sign, err := crypto.Sign(&c.key.PrivateKey, buf)
```
Comment (alexvanin) [inline internal/neofs/tree_signature.go:10]: Add a comment there.

```
// crypto package should not be used outside of API libraries (see neofs-node#491).
// For now tree service does not include into SDK Client nor SDK Pool, so there is no choice.
// When SDK library adopts Tree service client, this should be dropped.

**Review by alexvanin — APPROVED** [review]

**Review by masterSplinter01 — APPROVED** [review]

**Review by alexvanin — APPROVED** [review]
