### PR TITLE
[#198] Fix object metadata

### LINKED ISSUE #198: Improve metadata support
The following tests (#150) should pass:
* s3tests_boto3.functional.test_s3.test_object_set_get_metadata_none_to_good
* s3tests_boto3.functional.test_s3.test_object_set_get_metadata_none_to_empty
* s3tests_boto3.functional.test_s3.test_object_set_get_metadata_overwrite_to_empty

related #131

### PR DESCRIPTION
**Pull request by KirillovDenis**
The following test now pass: 
* s3tests_boto3.functional.test_s3:test_object_set_get_metadata_none_to_good

closes #198 

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

**Review by realloc — APPROVED** [review]

File: api/handler/get.go [hunk 1]
```diff
@@ -73,7 +73,7 @@ func writeHeaders(h http.Header, info *layer.ObjectInfo) {
 	h.Set(api.ETag, info.HashSum)
 
 	for key, val := range info.Headers {
-		h.Set(api.MetadataPrefix+key, val)
+		h[api.MetadataPrefix+key] = []string{val}
```
Comment (alexvanin) [inline api/handler/get.go:76]: `api.MetadataPrefix+key` should not be canonized? Maybe it worth extra comment in code?

Edit 1: Okay, too late, it is merged already :smile:

Comment (KirillovDenis) [reply api/handler/get.go:76]: > `api.MetadataPrefix+key` should not be canonized? Maybe it worth extra comment in code?
> 
> Edit 1: Okay, too late, it is merged already

[Amazon S3 stores user-defined metadata keys in lowercase.](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata)
