### PR TITLE
Remove metafiles when deleting object

### LINKED ISSUE #1158: Tag objects are not deleted when deleting an object
## Current Behavior
Object is deleted, but tag object for it is left.

## Expected Behavior
No objects left behind.

## Possible Solution
Find and drop appropriate tag object. Do not make additional searches.

## Steps to Reproduce
Put an object. Put tags for it. Delete object. Check container contents.

### PR DESCRIPTION
**Pull request by smallhive**
Closes #1158.

### CODE REVIEW

File: api/layer/layer.go [hunk 1]
```diff
@@ -920,6 +938,22 @@ func (n *layer) deleteObject(ctx context.Context, bkt *data.BucketInfo, settings
 	}
 	n.cache.DeleteObjectName(bkt.CID, bkt.Name, obj.Name)
 
+	ov := ObjectVersion{
+		BktInfo:    bkt,
+		ObjectName: obj.Name,
+	}
+
+	if err = n.DeleteObjectMetaFiles(ctx, &ov); err != nil {
```
Comment (roman-khimov) [inline api/layer/layer.go:946]: No additional search in this case, please.

**Review by roman-khimov — CHANGES_REQUESTED** [review]

File: api/layer/layer.go (hunk 1 above)
Comment (smallhive) [reply api/layer/layer.go:946]: How to find all metafiles without search?

Comment (roman-khimov) [reply api/layer/layer.go:946]: You're making a search above in `n.searchAllVersionsInNeoFS()`. It should be sufficient to find meta files as well.

Comment (smallhive) [reply api/layer/layer.go]: Reworked

File: api/layer/object.go [hunk 2]
```diff
@@ -1417,3 +1417,99 @@ func extractLockDataFromAttrubute(lsr *locksSearchResult, attributeValue string)
...
+		return fmt.Errorf("search object version: %w", err)
+	}
+
+	if len(res) == 0 {
+		return nil
+	}
+
+	for i := range res {
+		if err = n.objectDelete(ctx, p.BktInfo, res[i].ID); err != nil {
+			return fmt.Errorf(
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/object.go]: It makes sence, updated

File: api/layer/object.go [hunk 3]
```diff
@@ -1417,3 +1417,99 @@ func extractLockDataFromAttrubute(lsr *locksSearchResult, attributeValue string)
...
+	if len(searchResultItems) == 0 {
+		return nil, ErrNodeNotFound
+	}
+
+	var (
+		oids = make([]oid.ID, 0, len(searchResultItems))
+	)
+
+	for _, item := range searchResultItems {
+		if len(item.Attributes) != len(returningAttributes) {
```
[the remark this answers is not in the document]
Comment (smallhive) [reply api/layer/object.go]: Removed

**Review by roman-khimov — APPROVED** [review]
