### PR TITLE
[#306] Handle empty post policy

### LINKED ISSUE #306: Incorrect empty policy handling
Cannot handle empty post policy. It seems we just forget use appropriate flag

So we need use it (in `checkPostPolicy` function):
```
policy := &postPolicy{empty: true}
if policyStr := auth.MultipartFormValue(r, "policy"); policyStr != "" {
	// ...
	policy.empty = false
}
```

### PR DESCRIPTION
**Pull request by KirillovDenis**
Add handling empty post policy
If this PR will be merged after https://github.com/nspcc-dev/neofs-sdk-go/pull/122 (and sdk version will be updated in s3-gw) we can update test results for:
* `test_s3.test_post_object_anonymous_request`
* `test_s3.test_post_object_set_success_code`

closes #306 

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

File: api/handler/put_test.go [hunk 1]
```diff
@@ -86,3 +89,18 @@ func TestCustomJSONMarshal(t *testing.T) {
 
 	require.Equal(t, expectedPolicy, policy)
 }
+
```
Comment (alexvanin) [inline api/handler/put_test.go:92]: Should we also replace `policy := &postPolicy{}` to `policy :=  &postPolicy{empty: true}` in line 86, even though it doesn't affect the test?

**Review by alexvanin — APPROVED** [review]

File: api/handler/put_test.go (hunk 1 above)
Comment (KirillovDenis) [reply api/handler/put_test.go:92]: I'm not sure because not empty policy is tested there.

**Review by realloc — APPROVED** [review]
