### PR TITLE
[#452] Fix tests

### LINKED ISSUE #452: Fix tests
After #451 we should fix tests and drop all unused code (e.g. old versioning approach)

### PR DESCRIPTION
**Pull request by KirillovDenis**
There is not any `search` anymore

close #452

### CODE REVIEW

File: api/layer/tree_mock.go [hunk 1]
```diff
@@ -1,8 +1,7 @@
-package tree
+package layer
```
Comment (alexvanin) [inline api/layer/tree_mock.go:1]: What the idea behind moving it into `layer` package? `neofs_mock.go` is still in `neofstest` package meanwhile.

File: api/handler/object_list.go [hunk 2]
```diff
@@ -281,7 +281,7 @@ func encodeListObjectVersionsToResponse(info *layer.ListObjectVersionsInfo, buck
 				DisplayName: ver.Object.Owner.String(),
 			},
 			Size:      ver.Object.Size,
-			VersionID: ver.Object.NullableVersion(),
+			VersionID: ver.Object.Version(), // todo return "null" version for unversioned
```
Comment (alexvanin) [inline api/handler/object_list.go:284]: Mention #474

File: api/layer/tree_mock.go (hunk 1 above)
Comment (KirillovDenis) [reply api/layer/tree_mock.go:1]: Cyclic dependency. Like https://github.com/nspcc-dev/neofs-s3-gw/issues/438

**Review by alexvanin — APPROVED** [review]
